// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
  storjSidebar: [
    {type: 'ref', label: '<-回到主页', id: 'feat'},
    {type: 'autogenerated', dirName: 'cryptocurrency/storj'}
  ],

  // But you can create a sidebar manually
  // storj: [
  //   'cryptocurrency/storj/1-intro-storj',
  //   {
  //     type: 'link',
  //     label: 'offical site',
  //     href: 'https://www.storj.io/'
  //   }
  // ]


  
  // mainSidebar: [
  //   'feat',
  //   {
  //     type: 'category',
  //     label: '加密货币',
  //     items: [
  //       'cryptocurrency/storj/intro-storj',
  //       {
  //         type: 'link',
  //         label: 'storj项目官网',
  //         href: 'https://www.storj.io/'
  //       },
  //     ],
  //   },
  // ],
   
};

export default sidebars;
